### PR TITLE
INTMDB-28: Added CRUD functions for Triggers

### PR DESCRIPTION
**Pull request by coderGo93**
Added Get, Create, Update and Delete for EventTriggers
## Proposed changes

_Jira ticket:_ INTMDB-28

Closes #[issue number]

## Checklist

- [] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by gssbzn — APPROVED** [review]
LGTM

**Review by themantissa — APPROVED** [review]
LGTM! TY!

**Comment by coderGo93** [comment]
Hi @themantissa @gssbzn , I re-requested because I have to make some changes since the docs seems different than in reality and I added a check response for errors because it was using from atlas and the errors from realm response is different

**Review by themantissa — APPROVED** [review]
@gssbzn fyi this is a re-review. Turns out a lot of the realm docs were out of date I guess.

**Review by gssbzn — APPROVED** [review]
LGTM

**Review by abner-dou — APPROVED** [review]

**Pull request merged**
